using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using SkyBuy.Common.Helpers;

namespace SkyBuy.Data.Model.Entities
{
    public class FlightSchedule
    {
        
        [Key]
        public int Id { get; set; }  


        // Foreign Keys

        public int FlightServiceId { get; set; }
        public FlightService FlightService { get; set; } = null!;

        public string AircraftTypeICAO { get; set; } = null!; // Which type of plane will be used
        public AircraftType AircraftType { get; set; } = null!;

        public int? PreviousLegId { get; set; }
        public FlightSchedule? PreviousLeg { get; set; } // previous linked with schedule 


        // Schedule-specific data

        [Required]
        public TimeSpan LocalDepartureTime { get; set; }

        [Required]
        public DaysOfWeek OperatingDays { get; set; }  /// DaysOfWeek.Monday | DaysOfWeek.Friday



        [Required]
        public DateOnly ValidFrom { get; set; } // depends on season

        [Required]
        public DateOnly ValidUntil { get; set; }

        [Required]
        public decimal BasePrice { get; set; }
        
        [Required]
        public bool IsAutoGenerated { get; set; }

        [Required]
        public bool IsActive { get; set; } = true;


        // Navigation
        public ICollection<Flight> Flights { get; set; } = new List<Flight>();
        
    }

    
}
