using Microsoft.EntityFrameworkCore;
using SkyBuy.Common.Helpers;
using SkyBuy.Data.Data;
using SkyBuy.Data.Model.DTOs;
using SkyBuy.Data.Model.Entities;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Text;
using TimeZoneConverter;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace SkyBuy.Services
{
    public class ScheduleService
    {

        private readonly SkyBuyContext _dbContext; 
        private readonly AirLabsClient _airLabsClient;
        private readonly AirportsClient _airportsClient;
        private readonly AeroDataBoxClient _aeroDataBoxClient;
        private readonly AirplaneFlightService _airplaneFlightService;

        public ScheduleService(SkyBuyContext dbContext, AirLabsClient airLabsClient, AirportsClient airportsClient,AeroDataBoxClient aeroDataBoxClient,
                               AirplaneFlightService airplaneFlightService)
        { 
            _dbContext = dbContext;
            _airLabsClient = airLabsClient;
            _airportsClient = airportsClient;
            _aeroDataBoxClient = aeroDataBoxClient;
            _airplaneFlightService= airplaneFlightService;
        }



        /// Add schedule
        public async Task<(bool Success, List<string>? Errors)> GenerateFlightsScheduleAsync(ScheduleDTO scheduleDTO)
        {
            List<string> Errors = new List<string>();

            using var transaction = await _dbContext.Database.BeginTransactionAsync();

            try
            {
                var originicaoTask = _airportsClient.AirportCodeFromCodeAsync("IATA", scheduleDTO.OriginIATA);
                var desticaoTask = _airportsClient.AirportCodeFromCodeAsync("IATA", scheduleDTO.DestinationIATA);

                await Task.WhenAll(originicaoTask, desticaoTask);

                var OriginIcao = await originicaoTask;
                var DestIcao = await desticaoTask;

                if (OriginIcao == null || DestIcao == null)
                {
                    Errors.Add("Error resolving Airport ICAO codes.");
                    return (false, Errors);
                }

                ///  OUTBOUND ROUTE
                var route = await _dbContext.Routes.FirstOrDefaultAsync(el => el.DestinationICAO == DestIcao && el.OriginICAO == OriginIcao);

                if (route == null)
                {
                    route = new Route()
                    {
                        OriginICAO = OriginIcao,
                        DestinationICAO = DestIcao,
                        DistanceKm = scheduleDTO.ScheduleTimes.Distance,
                        TypicalDuration = (TimeSpan)scheduleDTO.ScheduleTimes.Duration
                    };
                    await _dbContext.Routes.AddAsync(route);
                }

                FlightService NewFlightServiceObj = new FlightService()
                {
                    Route = route,
                    AirlineICAO = scheduleDTO.SelectedRoute.AirlineICAO,
                    FlightNumber = int.Parse(scheduleDTO.SelectedRoute.FlightNumber),
                    FlightIATA = scheduleDTO.SelectedRoute.FlightIATA,
                    FlightICAO = scheduleDTO.SelectedRoute.FlightICAO
                };
                await _dbContext.FlightServices.AddAsync(NewFlightServiceObj);

                FlightSchedule Schedule = new FlightSchedule()
                {
                    FlightService = NewFlightServiceObj,
                    AircraftTypeICAO = scheduleDTO.SelectedAircraftICAO,
                    LocalDepartureTime = scheduleDTO.ScheduleTimes.LocalDepartureTime.Value,
                    OperatingDays = scheduleDTO.DaysOfWeekMask,
                    ValidFrom = DateOnly.FromDateTime(scheduleDTO.Season.Item1),
                    ValidUntil = DateOnly.FromDateTime(scheduleDTO.Season.Item2),
                    BasePrice = (decimal)scheduleDTO.BaseReferencePrice,
                    IsAutoGenerated = scheduleDTO.IsAutoGenerated
                };

                await _dbContext.FlightSchedules.AddAsync(Schedule);

                /// INBOUND (RETURN) SHUTTLE
                FlightSchedule? ScheduleInbound = null;
                if (scheduleDTO.SelectedReturnShuttle)
                {
                    var routeBack = await _dbContext.Routes.FirstOrDefaultAsync(el => el.DestinationICAO == OriginIcao && el.OriginICAO == DestIcao);

                    if (routeBack == null)
                    {
                        /// recalculate dist/time
                        var DistTimeBack = await GetDistanceTimeAsync(new FlightRouteParametersDTO()
                        {
                            DepartureAirport_IATA = scheduleDTO.DestinationIATA,
                            ArrivalAirport_IATA = scheduleDTO.OriginIATA,
                            AircraftTypeICAO = scheduleDTO.SelectedAircraftICAO
                        });

                        if (!DistTimeBack.Ok)
                        {
                            Errors.Add(DistTimeBack.ErrorMsg ?? "Error calculating return route");
                            return (false, Errors);
                        }

                        routeBack = new Route()
                        {
                            OriginICAO = DestIcao,
                            DestinationICAO = OriginIcao,
                            DistanceKm = DistTimeBack.DistanceKm.Value,
                            TypicalDuration = TimeSpan.Parse(DistTimeBack.Duration)
                        };
                        await _dbContext.Routes.AddAsync(routeBack);
                    }

                    var returnData = ReturnFlightNumbers(scheduleDTO.SelectedRoute);
                    FlightService NewFlightServiceBackObj = new FlightService()
                    {
                        Route = routeBack,
                        AirlineICAO = returnData.AirlineICAO,
                        FlightNumber = int.Parse(returnData.FlightNumber),
                        FlightIATA = returnData.FlightIATA,
                        FlightICAO = returnData.FlightICAO
                    };
                    await _dbContext.FlightServices.AddAsync(NewFlightServiceBackObj);

                    ScheduleInbound = new FlightSchedule()
                    {
                        FlightService = NewFlightServiceBackObj,
                        AircraftTypeICAO = scheduleDTO.SelectedAircraftICAO,
                        LocalDepartureTime = scheduleDTO.ScheduleTimes.LocalArrivalTime.Value.Add(new TimeSpan(0, 50, 0)),
                        OperatingDays = scheduleDTO.DaysOfWeekMask,
                        ValidFrom = DateOnly.FromDateTime(scheduleDTO.Season.Item1),
                        ValidUntil = DateOnly.FromDateTime(scheduleDTO.Season.Item2),
                        BasePrice = (decimal)scheduleDTO.BaseReferencePrice,
                        IsAutoGenerated = scheduleDTO.IsAutoGenerated,
                        PreviousLeg = Schedule
                    };
                    await _dbContext.FlightSchedules.AddAsync(ScheduleInbound);
                }

     
                ///Save changes to assign IDs to the Schedule objects
                await _dbContext.SaveChangesAsync();

                /// GENERATE INDIVIDUAL FLIGHTS (OUTBOUND)
                var outboundInfo = new ScheduleDataForFlightsDTO()
                {
                    FlightScheduleId = Schedule.Id,
                    LocalDepartureTime = Schedule.LocalDepartureTime,
                    OperatingDays = Schedule.OperatingDays,
                    ValidFrom = Schedule.ValidFrom,
                    ValidUntil = Schedule.ValidUntil,
                    AircraftTypeICAO = Schedule.AircraftTypeICAO,
                    CurrentPrice = Schedule.BasePrice,
                    TypicalDuration = (TimeSpan)scheduleDTO.ScheduleTimes.Duration,
                    OriginIATA = scheduleDTO.OriginIATA
                };

                var resultOut = await _airplaneFlightService.GenerateIndividualFlights(outboundInfo, _dbContext);
                if (!resultOut.Item1)
                {
                    Errors.Add(resultOut.Item2 ?? "Outbound flight generation error");
                    return (false, Errors);
                }

                /// GENERATE INDIVIDUAL FLIGHTS (INBOUND)
                if (ScheduleInbound != null)
                {
                    var inboundInfo = new ScheduleDataForFlightsDTO()
                    {
                        FlightScheduleId = ScheduleInbound.Id,
                        LocalDepartureTime = ScheduleInbound.LocalDepartureTime,
                        OperatingDays = ScheduleInbound.OperatingDays,
                        ValidFrom = ScheduleInbound.ValidFrom,
                        ValidUntil = ScheduleInbound.ValidUntil,
                        AircraftTypeICAO = ScheduleInbound.AircraftTypeICAO,
                        CurrentPrice = ScheduleInbound.BasePrice,
                        TypicalDuration = (TimeSpan)scheduleDTO.ScheduleTimes.Duration,
                        OriginIATA = scheduleDTO.DestinationIATA
                    };

                    var resultIn = await _airplaneFlightService.GenerateIndividualFlights(inboundInfo, _dbContext);
                    if (!resultIn.Item1)
                    {
                        Errors.Add(resultIn.Item2 ?? "Inbound flight generation error");
                        return (false, Errors);
                    }
                }
              
                await transaction.CommitAsync();
                return (true, null);
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();

                // Detailed error extraction
                var sb = new StringBuilder();
                sb.AppendLine($"Main Service Error: {ex.Message}");

                Exception? inner = ex.InnerException;
                while (inner != null)
                {
                    sb.AppendLine($"--> Database Details: {inner.Message}");
                    inner = inner.InnerException;
                }

                Errors.Add(sb.ToString());
                return (false, Errors);
            }
        }





        /// Quick Inbound Shuttle numbers
        private PartialScheduleJsonDTO ReturnFlightNumbers(PartialScheduleJsonDTO Leg1)
        {
            int flightNumber = int.Parse(Leg1.FlightNumber);
            flightNumber++;
            string Number = flightNumber.ToString();

            return new PartialScheduleJsonDTO()
            {
                AirlineIATA = Leg1.AirlineIATA,
                AirlineICAO = Leg1.AirlineICAO,
                FlightIATA = Leg1.AirlineIATA + Number,
                FlightICAO = Leg1.AirlineICAO + Number,
                FlightNumber = Number
            };
        }

        /// generate random number 
        private async Task<(string?,PartialScheduleJsonDTO?)> GeneratedFlightNumbers(string AirlineIATA)
        {
            Random rand = new Random();
            bool found = false;
            int flight_number = 0;
            string FlightIATA;
            string FlightICAO;
            
            try
            {
                while (true)
                {
                    flight_number = rand.Next(3000, 9000);
                    if (flight_number % 2 == 0) { ++flight_number; } /// OUTBOUND FLIGHT

                    FlightIATA = $"{AirlineIATA}{flight_number}"; /// W43044

                    found = await _dbContext.FlightServices
                        .AnyAsync(f => f.FlightIATA == FlightIATA);

                    if (!found) break; //schedule not added already
                }

                var AirlineICAO = await  _dbContext.Airlines.Where(element=>element.IATA == AirlineIATA).Select(a=>a.ICAO).FirstOrDefaultAsync();


                if (AirlineICAO == null)
                {
                    throw new Exception("Airline Icao not found error");
                }

                var FlightNumber = flight_number.ToString();
                FlightICAO = AirlineICAO + FlightNumber;

                PartialScheduleJsonDTO ids = new PartialScheduleJsonDTO()
                {
                    AirlineIATA = AirlineIATA,
                    AirlineICAO = AirlineICAO,
                    FlightIATA = FlightIATA,
                    FlightICAO = FlightICAO,
                    FlightNumber = FlightNumber
                };

                return (null, ids);

            }
            catch (Exception e)
            {
                Debug.WriteLine(e.ToString());
                if (e.InnerException != null)
                {
                    Debug.WriteLine("INNER: " + e.InnerException.Message);
                }
                return ("Error generating schedule data", null);
            }  
        }

        /// return partial schedule data , real or generated if non-existent or already added
        public async Task<(bool IsAutoGenerated,bool Found, string? ErrorMsg, List<PartialScheduleJsonDTO>? Routes)> GetAvailableRoutesAsync(FlightRouteParametersDTO data)
        {
            var RouteResult = await _airLabsClient.LoadRouteAsync(data); // load real routes parts that are not already inside db

            if (!RouteResult.Found && RouteResult.ErrorMsg != null)
            {
                /// System error
                return (false,false, RouteResult.ErrorMsg, null);
            }
            else if (!RouteResult.Found)
            {

                /// return randomly , non-existent generated one TODO
                var (msg, result) = await GeneratedFlightNumbers(data.Airline_IATA);

                if (msg != null) { return (false,false, msg, null); }

                return (true,true, null, new List<PartialScheduleJsonDTO> { result });
            }

            /// return list of found ones or not added ones
            return (false,true, null, RouteResult.Routes);

        }

        /// for selecting type of aircraft for schedule
        public async Task<HashSet<string>> GetAircraftICAOsAsync(string Airline_IATA)
        {
            return await _airLabsClient.GetAirplaneModelsAsync(Airline_IATA);
        }
        
        /// compute distance and time between endpoints
        public async Task<DistanceTimeResponseDTO> GetDistanceTimeAsync(FlightRouteParametersDTO data)
        {
            return await _aeroDataBoxClient.GetDistanceTimeAsync(data);
        }

        /// compute flight local and utc times based on inputs
        public async Task<ScheduleTimesDTO> CalculateScheduleTimesAsync(TimeSpan typedLocalTime, FlightRouteParametersDTO data)
        {
            try
            {
                var depTZTask = _airportsClient.GetTimezoneByCodeAsync("IATA", data.DepartureAirport_IATA);
                var arrTzTask = _airportsClient.GetTimezoneByCodeAsync("IATA", data.ArrivalAirport_IATA);
                var distTimetask = _aeroDataBoxClient.GetDistanceTimeAsync(data);

                await Task.WhenAll(depTZTask, arrTzTask, distTimetask);

                if (depTZTask.Result == null || arrTzTask.Result == null) { return new ScheduleTimesDTO() { OK = false, ErrorMsg = "Error retriving timezones" }; }
                if (!distTimetask.Result.Ok) { return new ScheduleTimesDTO() { OK = false, ErrorMsg = distTimetask.Result.ErrorMsg }; }

                var distTime = distTimetask.Result;

                /// timezone info + duration
                var depTzInfo = TimeZoneInfo.FindSystemTimeZoneById(TZConvert.IanaToWindows(depTZTask.Result));
                var arrTzInfo = TimeZoneInfo.FindSystemTimeZoneById(TZConvert.IanaToWindows(arrTzTask.Result));
                TimeSpan duration = TimeSpan.Parse(distTime.Duration);

                /// Bridge date : just a plain date with a time offset added, it does not know anything about location, utc etc
                DateTime referenceDate = DateTime.Today;
                DateTime localDepartureDateTime = DateTime.SpecifyKind(referenceDate.Add(typedLocalTime), DateTimeKind.Unspecified); /// Strip any hidden system offsets

                TimeSpan depOffset = depTzInfo.GetUtcOffset(localDepartureDateTime); /// based on that date-time what is the current airport UTC offset
                DateTimeOffset departureLocal = new DateTimeOffset(localDepartureDateTime, depOffset); /// glued Globally Unique Point in time
                DateTimeOffset departureUtc = departureLocal.ToUniversalTime(); /// This shifts the clock

                DateTimeOffset arrivalUtc = departureUtc.Add(duration);
                DateTimeOffset arrivalLocal = TimeZoneInfo.ConvertTime(arrivalUtc, arrTzInfo); /// conv utcn based on arrival time zone

                /// Extract the UTC 
                TimeSpan utcDepartureTime = departureUtc.TimeOfDay;
                TimeSpan utcArrivalTime = arrivalUtc.TimeOfDay;

                /// GUI Offsets
                string departureOffset = $"UTC{(depOffset.TotalHours >= 0 ? "+" : "")}{depOffset.TotalHours}";
                string arrivalOffset = $"UTC{(arrivalLocal.Offset.TotalHours >= 0 ? "+" : "")}{arrivalLocal.Offset.TotalHours}";

                return new ScheduleTimesDTO
                {
                    ArrivalTimeUTC = utcArrivalTime,
                    DepartureTimeUTC = utcDepartureTime,
                    LocalDepartureTime = departureLocal.TimeOfDay,
                    LocalArrivalTime = arrivalLocal.TimeOfDay,
                    Distance = distTime.DistanceKm ?? -1,
                    Duration = duration,
                    OK = true,
                    ArrivalOffsetString = arrivalOffset,
                    DepartureOffsetString = departureOffset,
                    IsArrivalNextDay = (arrivalLocal.Date - departureLocal.Date).Days >= 1
                };
            }
            catch(Exception e)
            {
                return new ScheduleTimesDTO() { OK = false, ErrorMsg = e.Message };
            }
        }
    }
}
