// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyBuy.Data.Data;

#nullable disable

namespace SkyBuy.Data.Migrations
{
    [DbContext(typeof(SkyBuyContext))]
    [Migration("20260120120940_FlightServUpd")]
    partial class FlightServUpd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [Username] IS NOT NULL");

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Account_LoginFields", "\r\n                        (\r\n                            (AccountType = 1 AND Email IS NOT NULL AND Username IS NULL) \r\n                            OR\r\n                            (AccountType = 2 AND Username IS NOT NULL)\r\n                        )\r\n                        ");
                        });
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.AircraftType", b =>
                {
                    b.Property<string>("ICAO")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<int>("TypicalSeats")
                        .HasColumnType("int");

                    b.HasKey("ICAO");

                    b.HasIndex("IATA")
                        .IsUnique();

                    b.HasIndex("Manufacturer");

                    b.ToTable("AircraftTypes");

                    b.HasData(
                        new
                        {
                            ICAO = "A320",
                            FullName = "Airbus A320-200",
                            IATA = "320",
                            Manufacturer = "Airbus",
                            MaxSeats = 186,
                            TypicalSeats = 180
                        },
                        new
                        {
                            ICAO = "A321",
                            FullName = "Airbus A321-200",
                            IATA = "321",
                            Manufacturer = "Airbus",
                            MaxSeats = 220,
                            TypicalSeats = 200
                        },
                        new
                        {
                            ICAO = "A20N",
                            FullName = "Airbus A320neo",
                            IATA = "32N",
                            Manufacturer = "Airbus",
                            MaxSeats = 194,
                            TypicalSeats = 180
                        },
                        new
                        {
                            ICAO = "A21N",
                            FullName = "Airbus A321neo",
                            IATA = "32Q",
                            Manufacturer = "Airbus",
                            MaxSeats = 244,
                            TypicalSeats = 206
                        });
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Airline", b =>
                {
                    b.Property<string>("ICAO")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryISO")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ICAO");

                    b.HasIndex("IATA")
                        .IsUnique();

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            ICAO = "WZZ",
                            Country = "Hungary",
                            CountryISO = "HU",
                            IATA = "W6",
                            Name = "Wizz Air Hungary"
                        },
                        new
                        {
                            ICAO = "WMT",
                            Country = "Malta",
                            CountryISO = "MLT",
                            IATA = "W4",
                            Name = "Wizz Air Malta"
                        });
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Airport", b =>
                {
                    b.Property<string>("ICAO")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryISO")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("Elevation")
                        .HasColumnType("int");

                    b.Property<string>("IATA")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ICAO");

                    b.HasIndex("City")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("CountryISO")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("IATA")
                        .IsUnique()
                        .HasFilter("[IATA] IS NOT NULL AND [IsActive] = 1");

                    b.HasIndex("ICAO")
                        .IsUnique()
                        .HasFilter("[ICAO] IS NOT NULL AND [IsActive] = 1");

                    b.HasIndex("Name")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("Lat", "Long")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BookingReference")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 ");

                    b.HasIndex("FlightId");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Booking_PassengerCount", "[NumberOfPassengers] > 0 AND [NumberOfPassengers] <= 5");

                            t.HasCheckConstraint("CK_Booking_Price", "[TotalPrice] >= 0");
                        });
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.FleetAircraft", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AircraftTypeICAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("AirlineICAO")
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("RegistrationNumber");

                    b.HasIndex("AircraftTypeICAO");

                    b.HasIndex("AirlineICAO");

                    b.ToTable("FleetAircrafts");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActualArrivalTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ActualDepartureTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ArrivalDateTimeUTC")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("DepartureDateTimeUTC")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FleetAircraftRegistrationNumber")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FlightScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Gate")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatsBooked")
                        .HasColumnType("int");

                    b.Property<int>("SeatsReserved")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Terminal")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalDateTimeUTC");

                    b.HasIndex("DepartureDateTimeUTC");

                    b.HasIndex("FleetAircraftRegistrationNumber");

                    b.HasIndex("FlightScheduleId");

                    b.ToTable("Flights", t =>
                        {
                            t.HasCheckConstraint("CK_Flight_Price_Positive", "[CurrentPrice] >= 0");

                            t.HasCheckConstraint("CK_Flight_Seats", "[SeatsBooked] + [SeatsReserved] <= [TotalSeats]");
                        });
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.FlightSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftTypeICAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FlightServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("LocalDepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("OperatingDays")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousLegId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AircraftTypeICAO");

                    b.HasIndex("FlightServiceId");

                    b.HasIndex("LocalDepartureTime")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("OperatingDays")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("PreviousLegId")
                        .IsUnique()
                        .HasFilter("[PreviousLegId] IS NOT NULL");

                    b.ToTable("FlightSchedules", t =>
                        {
                            t.HasCheckConstraint("CK_Schedule_Dates", "[ValidUntil] > [ValidFrom]");

                            t.HasCheckConstraint("CK_Schedule_Price", "[BasePrice] >= 0");
                        });
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.FlightService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirlineICAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("FlightIATA")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FlightICAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineICAO");

                    b.HasIndex("FlightIATA")
                        .IsUnique();

                    b.HasIndex("FlightICAO")
                        .IsUnique();

                    b.HasIndex("FlightNumber")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.ToTable("FlightServices");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PersonGender")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("Email")
                        .HasFilter("[Email] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("PassportNumber")
                        .IsUnique()
                        .HasFilter("[PassportNumber] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("Phone")
                        .HasFilter("[Phone] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("FirstName", "LastName")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Passengers", t =>
                        {
                            t.HasCheckConstraint("CK_Passenger_Age", "DATEDIFF(YEAR, [DateOfBirth], GETDATE()) >= 0");
                        });
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[IsDeleted]=0");

                    b.HasIndex("FirstName", "LastName")
                        .HasFilter("[IsDeleted]=0");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationICAO")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("bit");

                    b.Property<string>("OriginICAO")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<TimeSpan>("TypicalDuration")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationICAO");

                    b.HasIndex("OriginICAO", "DestinationICAO")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Routes", t =>
                        {
                            t.HasCheckConstraint("CK_Route_NotSameAirport_ICAO", "[OriginICAO] <> [DestinationICAO]");
                        });
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Booking", b =>
                {
                    b.HasOne("SkyBuy.Data.Model.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyBuy.Data.Model.Entities.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.FleetAircraft", b =>
                {
                    b.HasOne("SkyBuy.Data.Model.Entities.AircraftType", "AircraftType")
                        .WithMany("FleetAircrafts")
                        .HasForeignKey("AircraftTypeICAO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyBuy.Data.Model.Entities.Airline", "Airline")
                        .WithMany("FleetAircrafts")
                        .HasForeignKey("AirlineICAO");

                    b.Navigation("AircraftType");

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Flight", b =>
                {
                    b.HasOne("SkyBuy.Data.Model.Entities.FleetAircraft", "FleetAircraft")
                        .WithMany("Flights")
                        .HasForeignKey("FleetAircraftRegistrationNumber");

                    b.HasOne("SkyBuy.Data.Model.Entities.FlightSchedule", "FlightSchedule")
                        .WithMany("Flights")
                        .HasForeignKey("FlightScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FleetAircraft");

                    b.Navigation("FlightSchedule");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.FlightSchedule", b =>
                {
                    b.HasOne("SkyBuy.Data.Model.Entities.AircraftType", "AircraftType")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("AircraftTypeICAO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBuy.Data.Model.Entities.FlightService", "FlightService")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("FlightServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyBuy.Data.Model.Entities.FlightSchedule", "PreviousLeg")
                        .WithOne()
                        .HasForeignKey("SkyBuy.Data.Model.Entities.FlightSchedule", "PreviousLegId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AircraftType");

                    b.Navigation("FlightService");

                    b.Navigation("PreviousLeg");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.FlightService", b =>
                {
                    b.HasOne("SkyBuy.Data.Model.Entities.Airline", "Airline")
                        .WithMany("FlightServices")
                        .HasForeignKey("AirlineICAO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBuy.Data.Model.Entities.Route", "Route")
                        .WithMany("FlightServices")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Passenger", b =>
                {
                    b.HasOne("SkyBuy.Data.Model.Entities.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Profile", b =>
                {
                    b.HasOne("SkyBuy.Data.Model.Entities.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("SkyBuy.Data.Model.Entities.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Route", b =>
                {
                    b.HasOne("SkyBuy.Data.Model.Entities.Airport", "Destination")
                        .WithMany("DestinationRoutes")
                        .HasForeignKey("DestinationICAO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBuy.Data.Model.Entities.Airport", "Origin")
                        .WithMany("OriginRoutes")
                        .HasForeignKey("OriginICAO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Account", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.AircraftType", b =>
                {
                    b.Navigation("FleetAircrafts");

                    b.Navigation("FlightSchedules");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Airline", b =>
                {
                    b.Navigation("FleetAircrafts");

                    b.Navigation("FlightServices");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Airport", b =>
                {
                    b.Navigation("DestinationRoutes");

                    b.Navigation("OriginRoutes");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Booking", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.FleetAircraft", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Flight", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.FlightSchedule", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.FlightService", b =>
                {
                    b.Navigation("FlightSchedules");
                });

            modelBuilder.Entity("SkyBuy.Data.Model.Entities.Route", b =>
                {
                    b.Navigation("FlightServices");
                });
#pragma warning restore 612, 618
        }
    }
}
