using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using SkyBuy.Data.Model.DTOs;
using SkyBuy.Data.Model.Entities;
using SkyBuy.Models;
using SkyBuy.Services;
using SkyBuy.Common.Helpers;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using Windows.Globalization.DateTimeFormatting;
using Windows.UI.Xaml;


namespace SkyBuy.ViewModel
{

    public partial class SchedulePlanificationViewModel : ObservableObject
    {

        private readonly ScheduleService _scheduleService;
        internal string Airline_Division_Iata { get; set; }

       
        ///  avalabile from    :   to
        private Tuple<DateTime, DateTime> WinterSeason; 
        private Tuple<DateTime, DateTime> SummerSeason;

        public SchedulePlanificationViewModel(ScheduleService scheduleService)
        {
            _scheduleService=scheduleService;
        }   
       
        
        


        /// APP
        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(NotLoading))]
        public partial bool Loading { get; set; }
        public bool NotLoading => !Loading;

        [ObservableProperty]
        public partial bool HasErrors { get; set; }
        
        [ObservableProperty]
        public partial bool ShowScheduleTimes { get; set; }

        [ObservableProperty]
        public partial bool GoodData { get; set; } = false;

        [ObservableProperty]
        public partial bool ScheduleCodesAutoGenerated { get; set; }

        [ObservableProperty]
        public partial ObservableCollection<string> ValidationErrors { get; set; } = new ObservableCollection<string>();

        private List<string> _errors = new List<string>();
        

        
        

        



        // Step 1: Route Selection
        [ObservableProperty]
        public partial string OriginIATA {  get; set; }

        [ObservableProperty]
        public partial string DestinationIATA { get; set; }



        // Flight Selection from API
        [ObservableProperty]
        public partial ObservableCollection<PartialScheduleJsonDTO> RouteOptions {  get; set; } = new ObservableCollection<PartialScheduleJsonDTO>();       

        [ObservableProperty]
        public partial PartialScheduleJsonDTO SelectedRoute { get; set; }



        // Flight Days
        [ObservableProperty]
        public partial ObservableCollection<FlightDayItem> DayOptions { get; set; } =
        [
            new() { Name = "Monday",Value=1 },
            new() { Name = "Tuesday",Value=2},
            new() { Name = "Wednesday",Value=4},
            new() { Name = "Thursday",Value=8},
            new() { Name = "Friday",Value=16},
            new() { Name = "Saturday",Value=32},
            new() { Name = "Sunday",Value=64}
        ];

        

        // Aircraft type to be linked with schedule
        [ObservableProperty]
        public partial ObservableCollection<string> AircraftICAOs { get; set; } = new ObservableCollection<string>();

        [ObservableProperty]
        public partial string SelectedAircraftICAO { get; set; }


        // Local Time
        [ObservableProperty]
        public partial TimeSpan SelectedDepartureLocalTime { get; set; }

        [ObservableProperty]
        public partial ScheduleTimesDTO ScheduleTimes {  get; set; }





        // 0 winter , 1 summer
        [ObservableProperty]
        public partial int SelectedIndexSeason { get; set; } = 0;

        [ObservableProperty]
        public partial string WinterIntervalString { get; set; }

        [ObservableProperty]
        public partial string SummerIntervalString { get; set; }




        // Reference Seat Pice
        [ObservableProperty]
        public partial double SelectedBaseReferencePrice {  get; set; }






        /// if selected auto generate schedule after 45 min , on same days
        [ObservableProperty]
        public partial bool SelectedReturnShuttle {  get; set; } 


      
        /// Prop. Triggers
        ///////////////////////////////////////
        partial void OnSelectedDepartureLocalTimeChanged(TimeSpan value)
        {
            _ = CalculateTimesAsync();
        }
        partial void OnOriginIATAChanged(string value)
        {
            _ = CalculateTimesAsync();
        }
        partial void OnDestinationIATAChanged(string value)
        {
            _ = CalculateTimesAsync();
        }
        ///////////////////////////////////////

        // Commands
        [RelayCommand]
        private async Task CreateSchedule()
        {
            ClearErrors();
            Loading = true;
            GoodData = false;
            
            try
            {
                var mask = ReturnFlightDaysBitMask();

                if (mask==null)
                {
                    _errors.Add("Select schedule days!");
                    HasErrors = true;
                    return;
                }

                var DTO = new ScheduleDTO()
                {
                    SelectedRoute = SelectedRoute,
                    DaysOfWeekMask = mask.Value,
                    SelectedAircraftICAO = SelectedAircraftICAO,
                    ScheduleTimes = ScheduleTimes,
                    BaseReferencePrice = SelectedBaseReferencePrice,
                    Season = (SelectedIndexSeason==0) ? WinterSeason : SummerSeason,
                    IsAutoGenerated = ScheduleCodesAutoGenerated,
                    SelectedReturnShuttle = SelectedReturnShuttle,
                    OriginIATA = OriginIATA,
                    DestinationIATA = DestinationIATA
                };


                var (ok, errors) = await _scheduleService.GenerateFlightsScheduleAsync(DTO);

                if (!ok)
                {
                    HasErrors = true;
                    _errors.AddRange(errors);
                    return;
                }

                GoodData = true;

            }
            catch (Exception ex)
            {
                HasErrors = true;
                _errors.Add($"Error creating schedule: {ex.Message}");
                if (ex.InnerException != null) { _errors.Add(ex.InnerException.Message); }
            }
            finally
            {
                foreach (var err in _errors) { ValidationErrors.Add(err); }
                Loading = false;
            }
            
        }
        [RelayCommand]
        private async Task FetchFlights()
        {
            Loading = true;
            RouteOptions.Clear(); /// reset flight options panel
            ClearErrors();

            try
            {
                if (string.IsNullOrEmpty(OriginIATA) || string.IsNullOrEmpty(DestinationIATA))
                {
                    HasErrors = true;
                    _errors.Add("Some Fields are empty!");
                    return;
                }

                var parameters = new FlightRouteParametersDTO()
                {
                    DepartureAirport_IATA = OriginIATA,
                    ArrivalAirport_IATA = DestinationIATA,
                    Airline_IATA = Airline_Division_Iata
                };

                
                var (IsAutoGenerated,found, errorMsg, routes) = await _scheduleService.GetAvailableRoutesAsync(parameters);
            
                if (!found && errorMsg != null) /// system error
                {
                    HasErrors = true;
                    _errors.Add(errorMsg);
                    return;
                }

                ScheduleCodesAutoGenerated = IsAutoGenerated;

                foreach (var route in routes) /// four real route or generated ids for one
                {
                    RouteOptions.Add(route);
                }
            }
            catch (Exception ex)
            {
                HasErrors = true;
                _errors.Add($"Error fetching flights: {ex.Message}");
            }
            finally
            {
                foreach (var err in _errors) { ValidationErrors.Add(err); }
                Loading = false;
            }
        }
        [RelayCommand]
        private void GoBack()
        {
            App.AdminNavigationService.GoBack();
        }




        /// Helpers
        private void ClearErrors()
        {
            HasErrors = false;
            ValidationErrors.Clear();
            _errors.Clear();
        }
        private async Task CalculateTimesAsync()
        {
            ShowScheduleTimes = false;

            if (string.IsNullOrEmpty(OriginIATA) || string.IsNullOrEmpty(DestinationIATA) ||
                string.IsNullOrEmpty(Airline_Division_Iata) || SelectedDepartureLocalTime == default) { return; }

            try
            {
                Loading = true;
                ShowScheduleTimes = false;
                ClearErrors();

                var flightRouteParameters = new FlightRouteParametersDTO()
                {
                    DepartureAirport_IATA = OriginIATA,
                    ArrivalAirport_IATA = DestinationIATA,
                    AircraftTypeICAO = SelectedAircraftICAO
                };

                var times = await _scheduleService.CalculateScheduleTimesAsync(SelectedDepartureLocalTime, flightRouteParameters);

                if (!times.OK)
                {
                    HasErrors = true;
                    _errors.Add(times.ErrorMsg);
                    return;
                }

                ScheduleTimes = times;
                ShowScheduleTimes = true;
            }
            catch (Exception ex)
            {
                HasErrors = true;
                _errors.Add(ex.Message);
            }
            finally
            {
                foreach (var err in _errors) { ValidationErrors.Add(err); }
                Loading = false;
            }
        }
        private DaysOfWeek? ReturnFlightDaysBitMask()
        {
            var selected_days = DayOptions.Where(el => el.IsChecked).Select(el => el.Value).ToHashSet();

            if (selected_days.IsNullOrEmpty()) /// none selected => error
            {
                return null;
            }

            DaysOfWeek first = (DaysOfWeek)selected_days.First();

            foreach (var day in selected_days.Skip(1))
            {
                first |= (DaysOfWeek)day;
            }

            return first; /// return bit mask
        }
        internal void InitSeasons()
        {
            var CurrentYear = DateTimeOffset.Now.Year;
            var NextYear = DateTimeOffset.Now.AddYears(1).Year;

            WinterSeason = new(new DateTime(CurrentYear, 10, 9), new DateTime(NextYear, 3, 29));
            SummerSeason = new(new DateTime(CurrentYear, 3, 29), new DateTime(CurrentYear, 10, 9));

            WinterIntervalString = $"{WinterSeason.Item1.ToString()}  ->  {WinterSeason.Item2.ToString()}";
            SummerIntervalString = $"{SummerSeason.Item1.ToString()}  ->  {SummerSeason.Item2.ToString()}";
        }
        internal void Set_Airline_Division_Iata(string airline)
        {
            Airline_Division_Iata = airline;
        }
        internal async Task InitAircraftICAOs(string Airline_IATA)
        {
            var ICAOs = await _scheduleService.GetAircraftICAOsAsync(Airline_IATA);

            foreach (var item in ICAOs)
                AircraftICAOs.Add(item);

        }

    }
}