using System;
using System.Collections.Generic;
using System.Text;
using SkyBuy.Common.Helpers;

namespace SkyBuy.Data.Model.DTOs
{
    public class ScheduleDTO
    {
        public required PartialScheduleJsonDTO SelectedRoute { get; set; }
        public required DaysOfWeek DaysOfWeekMask { get; set; }
        public required string SelectedAircraftICAO { get; set; }
        public required ScheduleTimesDTO ScheduleTimes { get; set; }
        public double BaseReferencePrice { get; set; }
        public required Tuple<DateTime, DateTime> Season {  get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool SelectedReturnShuttle { get; set; }
        public required string OriginIATA { get; set; } 
        public required string DestinationIATA { get; set; }

    }
}
